### ISSUE TITLE
Your website is broken

### ISSUE THREAD

**Issue by SteveAboveTheClouds** [shamlian/santabells#1]
I found your work while chasing down Santa Bells.

Your website: https://www.shamlian.net

shows this:

Fatal error: Array and string offset access syntax with curly braces is no longer supported in /home/public/app/parsers/markdown-parser.inc.php on line 944

**Comment by shamlian** [comment]
That's unfortunate; thanks for the heads up. I'm afraid other things have taken priority from keeping the site up to date. Likely it's time to start from scratch and rebuild.

**Comment by shamlian** [comment]
I've decided to use this as an opportunity to go from [stacey](https://github.com/kolber/stacey) to [jekyll](https://jekyllrb.com/), so it might be a little bit before the site is back to some semblance of normal. I've also committed the STLs that were on the original site to GitHub, though I'm guessing they're not much use to anyone but me. You can browse (most) of the site [on the wayback machine](https://web.archive.org/web/20211017003832/https://www.shamlian.net/projects/santabells/) while you wait!

**Comment by SteveAboveTheClouds** [comment]
Yup!  Been there and was pleasantly surprised by your breadth of musical
"toys".  I've been hacking musical and mechanical toys for a long time and
figured you would want to keep the site going for other tinkerers.  I look
forward to your "new and improved" site!

**Comment by shamlian** [comment]
While I work on a new vanity site, I was able to restore the old site as a static backup. That should buy me a little time...
